
debug: true

spring:
  application:
    name: farm_web
  datasource:
    url: jdbc:postgresql://localhost:5432/farm
    username: postgres
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true